/**
 * Styles partagés pour les composants du Wizard "Nouvelle Mesure".
 * Extrait de /app/frontend/app/chantier/[id]/new-mesure.tsx (refacto V3 — juin 2026).
 */
import { Platform, StyleSheet } from "react-native";
import { colors } from "@/src/theme";

export const wizardStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.bg },
  topBar: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10,
    borderBottomWidth: 1, borderBottomColor: colors.borderSubtle,
  },
  stepRow: { flexDirection: "row", gap: 8 },
  stepPill: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: colors.surfaceElevated,
    alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: colors.borderSubtle,
  },
  stepPillActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  stepPillText: { color: colors.textSecondary, fontWeight: "800", fontSize: 12 },
  reportBtn: {
    flexDirection: "row", alignItems: "center", gap: 4,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8,
    backgroundColor: "#2a1010", borderWidth: 1, borderColor: colors.anomaly,
  },
  reportBtnText: { color: colors.anomaly, fontSize: 11, fontWeight: "700" },
  h1: { color: colors.textPrimary, fontSize: 18, fontWeight: "800", letterSpacing: 0.5 },
  h2: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  sectionLabel: { color: colors.textSecondary, fontSize: 11, fontWeight: "900", letterSpacing: 0.8, marginBottom: 8 },
  errInline: { color: colors.anomaly, fontWeight: "900" },
  helperText: { color: colors.placeholder, fontSize: 12, marginBottom: 8, marginTop: 4, lineHeight: 16 },
  guideHint: {
    color: colors.textSecondary,
    fontSize: 11,
    fontStyle: "italic",
    textAlign: "center",
    marginTop: -2,
    marginBottom: 4,
    paddingHorizontal: 8,
  },
  label: { color: colors.textSecondary, fontSize: 11, fontWeight: "700", letterSpacing: 0.6, marginBottom: 6 },
  input: {
    backgroundColor: colors.inputBg, color: colors.textPrimary, borderRadius: 10,
    borderWidth: 1, borderColor: colors.borderStrong,
    paddingHorizontal: 12, paddingVertical: Platform.OS === "ios" ? 14 : 10,
    fontSize: 16, minHeight: 48,
  },
  inputError: { borderColor: colors.anomaly, backgroundColor: "#1a0808" },
  errorMsg: { color: colors.anomaly, fontSize: 11, fontWeight: "800", marginTop: 4, letterSpacing: 0.4 },
  row2: { flexDirection: "row", gap: 10 },
  segBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
    backgroundColor: colors.surface, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSubtle,
    paddingVertical: 12, paddingHorizontal: 8, minHeight: 48,
  },
  segBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  segBtnText: { color: colors.textSecondary, fontWeight: "800", fontSize: 12, letterSpacing: 0.4, textAlign: "center", flexShrink: 1 },
  facadeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  facadeCard: {
    width: "47%", backgroundColor: colors.surface, borderRadius: 10,
    borderWidth: 1, borderColor: colors.borderSubtle,
    paddingVertical: 14, paddingHorizontal: 10, alignItems: "center", gap: 6,
  },
  facadeCardActive: { borderColor: colors.primary, backgroundColor: "#1a0e05" },
  facadeLabel: { color: colors.textPrimary, fontWeight: "800", fontSize: 12, textAlign: "center", letterSpacing: 0.3 },
  insulOption: {
    flexDirection: "row", alignItems: "center", gap: 10,
    backgroundColor: colors.surface, borderRadius: 10,
    borderWidth: 1, borderColor: colors.borderSubtle,
    paddingVertical: 14, paddingHorizontal: 14, minHeight: 50,
  },
  insulOptionActive: { borderColor: colors.primary, backgroundColor: "#1a0e05" },
  insulOptionLabel: { color: colors.textPrimary, fontWeight: "800", fontSize: 13 },
  inlineHintBox: {
    flexDirection: "row", alignItems: "center", gap: 6, marginTop: 8,
    padding: 10, borderRadius: 8, backgroundColor: "#2a1c08",
    borderWidth: 1, borderColor: colors.warning,
  },
  inlineHintText: { color: colors.textSecondary, fontSize: 11, flex: 1, lineHeight: 15 },
  checkboxRow: {
    flexDirection: "row", alignItems: "center", gap: 12,
    paddingVertical: 12, paddingHorizontal: 14, borderRadius: 10,
    backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSubtle, marginTop: 8,
  },
  checkboxLabel: { color: colors.textPrimary, fontSize: 14, fontWeight: "700" },
  checkboxSub: { color: colors.textSecondary, fontSize: 11, marginTop: 2 },
  shapeCard: {
    flexDirection: "row", alignItems: "center", gap: 10,
    backgroundColor: colors.surface, borderRadius: 12,
    borderWidth: 1, borderColor: colors.borderSubtle, padding: 14, minHeight: 84,
  },
  shapeCardActive: { borderColor: colors.primary, backgroundColor: "#1a0e05" },
  shapeLetterBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  shapeLetter: { color: "#000", fontWeight: "900", fontSize: 12 },
  shapeIconBox: { width: 56, height: 56, alignItems: "center", justifyContent: "center" },
  shapeTitle: { color: colors.textPrimary, fontWeight: "900", fontSize: 14, letterSpacing: 0.4 },
  shapeDesc: { color: colors.textSecondary, fontSize: 11, marginTop: 2, lineHeight: 15 },
  modeToggle: {
    flexDirection: "row", gap: 6, marginTop: 14, padding: 4,
    backgroundColor: colors.surface, borderRadius: 10,
    borderWidth: 1, borderColor: colors.borderSubtle,
  },
  modeTab: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 10, borderRadius: 8 },
  modeTabActive: { backgroundColor: colors.primary },
  modeTabText: { color: colors.textSecondary, fontSize: 11, fontWeight: "900", letterSpacing: 0.6 },
  modeTabTextActive: { color: "#000" },
  sketchBox: { marginTop: 16, alignItems: "center", backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: colors.borderSubtle, paddingVertical: 12 },
  autoBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: colors.primary, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  validBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: colors.success, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  autoBadgeText: { color: "#000", fontSize: 10, fontWeight: "900", letterSpacing: 0.5 },
  diagBtn: { width: 48, height: 48, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  computeBtn: {
    marginTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 8, paddingVertical: 12, paddingHorizontal: 14, borderRadius: 10,
    borderWidth: 1, borderColor: colors.primary, backgroundColor: "#1a0e05",
  },
  computeBtnText: { color: colors.primary, fontWeight: "900", fontSize: 13, letterSpacing: 0.8 },
  computedBox: {
    flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6,
    marginTop: 12, padding: 12, borderRadius: 10,
    backgroundColor: "#0b3b1c", borderWidth: 1, borderColor: colors.success,
  },
  computedLabel: { color: colors.success, fontWeight: "900", fontSize: 11, letterSpacing: 0.5 },
  computedValue: { color: colors.success, fontWeight: "900", fontSize: 18 },
  computedFormula: { color: colors.textSecondary, fontSize: 11, fontStyle: "italic" },
  photo: { width: "100%", height: 180, borderRadius: 12, marginTop: 8 },
  removePhoto: { position: "absolute", top: 16, right: 8, backgroundColor: "rgba(0,0,0,0.7)", padding: 6, borderRadius: 14 },
  photoRow: { flexDirection: "row", gap: 8, marginTop: 8 },
  photoBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 14, borderRadius: 10, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSubtle },
  photoBtnText: { color: colors.primary, fontWeight: "700", fontSize: 13 },
  footer: { flexDirection: "row", gap: 10, padding: 16, borderTopWidth: 1, borderTopColor: colors.borderSubtle, backgroundColor: colors.bg },
  btn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, minHeight: 52, borderRadius: 12, paddingHorizontal: 16 },
  btnPrimary: { backgroundColor: colors.primary },
  btnPrimaryText: { color: "#000", fontWeight: "900", fontSize: 14, letterSpacing: 0.8 },
  btnSecondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderSubtle },
  // 🆕 V3 — Bouton secondaire utilisé pour les actions "feedback / remarque"
  //    sur les modules en cours de fabrication (Bow-window).
  btnSecondaryAlt: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 48,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface,
  },
  btnSecondaryAltText: {
    color: colors.textPrimary,
    fontWeight: "800",
    fontSize: 11,
    letterSpacing: 0.5,
    textAlign: "center",
    flexShrink: 1,
  },
  btnSecondaryText: { color: colors.textPrimary, fontWeight: "800", fontSize: 13, letterSpacing: 0.5 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.7)", justifyContent: "center", padding: 20 },
  modalCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 18, borderWidth: 1, borderColor: colors.borderSubtle },
  modalTitle: { color: colors.textPrimary, fontWeight: "800", fontSize: 16 },
  modalSub: { color: colors.textSecondary, fontSize: 12, marginTop: 4, marginBottom: 12 },
  reportInput: { backgroundColor: colors.inputBg, color: colors.textPrimary, borderRadius: 10, borderWidth: 1, borderColor: colors.borderStrong, padding: 12, minHeight: 100, textAlignVertical: "top", fontSize: 14 },
  // Style helpHint utilisé dans Step1Config — ajouté ici (manquait dans le fichier original).
  helpHint: {
    color: colors.textSecondary,
    fontSize: 11,
    fontStyle: "italic",
    lineHeight: 15,
    marginTop: 6,
    paddingHorizontal: 4,
  },
});
